### ISSUE TITLE
Change getSpacyData to output prefered format

### ISSUE THREAD

**Issue by pbaekgaard** [Knox-AAU/PreProcessingLayer_EntityRecognitionAndLinking#30]
Def. of done: 
Make so JSON outputted is how below format - AND IS TESTED - and the other group approves

Information so far (see message from jonas and assbear in #ontology-commitee):

de mangler i deres egne ord:
Vi mangler i hvert fald:
- den fulde sætning
- startIndex + endIndex for begge entity mentions i sætningen (index for hvert JSON objekt)

So make it so that the JSON file is of the following format

```json
[
    {
        "filename": "path/to/Artikel.txt",
        "sentences": [
            {
                "sentence": "Barrack Obama is married to Michelle Obama",
                "sentenceStartIndex": 20,
                "sentenceEndIndex": 62,
                "entityMentions": 
                [
                    { "name": "Barrack Obama", "startIndex": 0, "endIndex": 12, "linkId": 1 },
                    { "name": "Michelle Obama", "startIndex": 27, "endIndex": 40, "linkId": 2 }
                ]
            }
        ]
    }
]
```

**Comment by Aasmundur** [comment]
Also sentence start index in text
